question_data = [
    {"text": "In Generation 1 of Pokemon, Pikachu can be chosen as a starter.", "answer": "True", "justification": "In Pokemon Yellow."},
{"text": "Mew can be found under a truck within the restricted area of S.S. Anne.", "answer": "False",
    "justification": "A myth! A lava cookie was added in generation 3 as an easter egg for this widespread rumour!"},
{"text": "Winona is the 6th Gym Leader in Pokemon Emerald.", "answer": "True", "justification": "In Fortree City."},
{"text": "Koga uses Fighting-Type pokemon in his Gym.", "answer": "False", "justification": "Poison Types are used."},
{"text": "In Generation 1 of Pokemon, the Old Man catches a Weedle in his pokemon catching tutorial.", "answer": "True",
    "justification": "In Viridian City."},
{"text": "In Generation 1 of Pokemon, the Old Man catches a Caterpie in his pokemon catching tutorial.",
    "answer": "False", "justification": "It was a Weedle."},
{"text": "In Generation 3 of Pokemon, Wally catches a Ralts in his pokemon catching tutorial.", "answer": "True",
    "justification": "Beside Petalburg."},
{"text": "In Generation 3 of Pokemon, Wally catches a Zigzagoon in his pokemon catching tutorial.", "answer": "False",
    "justification": "It was a Ralts."},
{"text": "Blaziken is a Fire/Flying Type", "answer": "False", "justification": "Fire/Fighting Type"},
{"text": "Team Plasma was the villain in Pokemon Emerald", "answer": "False", "justification": "Team Magma/Aqua."},
{"text": "There is a total of 151 Pokemon in Generation 1", "answer": "True", "justification": "Correct."},
{"text": "There is a total of 386 Pokemon in Generation 3", "answer": "True", "justification": "Correct."},
{"text": "There are no double battles in Pokemon Sapphire", "answer": "False",
    "justification": "Double battles were already introduced"},
{"text": "Sabrina in Saffron City gives out the Marsh Badge", "answer": "True", "justification": "Correct."},
{"text": "The hometown of the player in Generation 2 is New Bark City",
    "answer": "False", "justification": "New Bark Town."},
{"text": "The hometown of the player in Generation 3 is Littleroot Town", "answer": "True", "justification": "Correct"},
]